### ISSUE TITLE
Array.prototype.indexOf() may not be available either

### ISSUE THREAD

**Issue by jhiesey** [ljharb/object-keys#14]
If someone is using this module where es5 isn't fully supported (which seems like the obvious use case) then Array.prototype.indexOf() may not be available either.

However, it is used here: https://github.com/ljharb/object-keys/blob/master/index.js#L28 causing an error, which makes this module much less helpful. How about a simple for loop instead?

**Comment by ljharb** [comment]
That is an excellent point which needs to be corrected. Thanks for pointing it out! I'll take care of this asap.

**Comment by ljharb** [comment]
Released as `v1.0.6`
