### ISSUE TITLE
Config files being published to npm

### ISSUE THREAD

**Issue by Jameskmonger** [ljharb/object-keys#21]
Currently the following files are all published on `npm`:

`.editorconfig`
`.eslintrc`
`.jscs.json`
`.travis.yml`

These are all developer-related config files rather than user-related, so they shouldn't be published to npm.

**Comment by ljharb** [comment]
`eslintrc` must be published to npm so that `npm run eslint` works when the module is installed.

All files should be published to npm.

**Comment by Jameskmonger** [comment]
There's no need for users of the package to run `npm run eslint`. This is a developer task to ensure developer code style of the module.

Tests, configuration files, and other files used only by the developers [should not be published to npm](http://www.rudeshko.com/web/2014/05/13/help-people-consume-your-npm-packages.html#anatomy-of-npm-package) to help prevent package bloat.

There is no need for a user to download configuration of your code style to use your package.

**Comment by ljharb** [comment]
There's certainly a need. `npm explore foo && npm install && npm test` should always work.

I'm aware of that article and that position, but I profoundly disagree with it. Package size is a consumer and an npm concern, not an author concern.

**Comment by Jameskmonger** [comment]
As said [my comment on #23](https://github.com/ljharb/object-keys/pull/23#discussion_r58567471), `npm run lint`, `npm run eslint` and `npm run jscs` will not work for people who install the module through `npm` because the dependencies that they need will not be installed with them.

**Comment by ljharb** [comment]
Again, `npm explore foo && npm install foo && npm run lint` will work perfectly.
