### ISSUE TITLE
Avoid reflow at accessing the window object

### ISSUE THREAD

**Issue by tanerin** [ljharb/object-keys#31]
Accessing all keys in the window object leads to an reflow at line 41 in [index.js](https://github.com/ljharb/object-keys/blob/master/index.js#L41). A fast and dirty workaround of me would be to avoid all attributes with with or height in it.

`if(k.toLowerCase().indexOf('width') > -1 || k.toLowerCase.indexOf('height') > -1) continue;`

As I don't understand the reason for the function completely I'm not really able to propose a correct pull request. That's why I just raised an issue. I hope that's okay.

**Comment by ljharb** [comment]
The purpose of the line is to locate browser bugs - the purpose of the blacklisted keys is to avoid accessing any problematic `window` keys. I wasn't aware that simply accessing `width` and/or `height` caused a reflow :-/ the proper solution will be to add them to the [exclusion list](https://github.com/ljharb/object-keys/blob/master/index.js#L24-L35).

**Comment by ljharb** [comment]
Thanks! Released in v1.0.10.
