### ISSUE TITLE
Outputs tons of errors in Chrome app environment

### ISSUE THREAD

**Issue by karel-3d** [ljharb/object-keys#34]
When I use object-keys in Chrome app (usually through some other package, but that doesn't matter really), it outputs all these errors:

> extensions::platformApp:17 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
> extensions::platformApp:17 window.toolbar is not available in packaged apps.
> extensions::platformApp:17 window.statusbar is not available in packaged apps.
> extensions::platformApp:17 window.scrollbars is not available in packaged apps.
> extensions::platformApp:17 window.personalbar is not available in packaged apps.
> extensions::platformApp:17 window.menubar is not available in packaged apps.
> extensions::platformApp:17 window.locationbar is not available in packaged apps.
> extensions::platformApp:17 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.

It comes from this part
https://github.com/ljharb/object-keys/blob/master/index.js#L46-L63

It seems window.localStorage etc. is "available" to list throuch for-in, but shows that error message on accessing it. (Not sure if it actually throws an error or not.)

It is a purely cosmetic bug and doesn't affect the functionality at all (it doesn't crash the application); however, it's not "nice" that it barfs all the bugs at the start

**Comment by runn1ng** [comment]
Yep, it doesn't throw an error, and window.localStorage is undefined, but it is in the window keys. See image, from Chrome app console

![vydz](https://cloud.githubusercontent.com/assets/104945/16837989/1478cf96-49c7-11e6-92a0-26c74b8b3e3b.png)

**Comment by ljharb** [comment]
Unfortunately, `localStorage` is the most important window key to enumerate, because it has a bug in IE 8 related to it - so I can't simply bypass it like I do other things that warn.

**Comment by karel-3d** [comment]
Btw, Chrome apps are being deprecated, but this also happens in chrome extensions.

**Comment by ljharb** [comment]
I'd still prefer to avoid it if we can find a way that doesn't involve browser sniffing.

**Comment by karel-3d** [comment]
I was wrong, this happens only in apps and not in extensions, I just tried that.

And Chrome Apps are being deprecated (you cannot even create a new one).

**Comment by ljharb** [comment]
I guess in that case we can close it :-/
