### ISSUE TITLE
Loading this shim on Chrome 67 will raise a warning

### ISSUE THREAD

**Issue by sylvhama** [ljharb/object-keys#46]
When using this code in my project:

```import objectKeys from 'object-keys';```

I will see this warning in Chrome 67.0.3396.87 console:
`index.js:51 [Deprecation] Application Cache is deprecated in non-secure contexts, and will be restricted to secure contexts in M69, around September 2018. Please consider migrating your application to HTTPS, and eventually shifting over to Service Workers. See https://goo.gl/rStTGz for more details.`

You can reproduce the warning by downloading this project https://codesandbox.io/s/kxp55lx90o and then do:
```
npm install
npm start
```

**Comment by ljharb** [comment]
Thanks; this is caused by enumerating enumerable keys on `window`, including `applicationCache`.
