### ISSUE TITLE
Missing LICENSE file in the repo of ver 0.4.0

### ISSUE THREAD

**Issue by itsuki-murata** [ljharb/object-keys#60]
Currently I'm using object-keys version 0.4.0, but can't find a LICENSE file in the repo of ver 0.4.0.
Could you add the LICENSE file in the repo of ver 0.4.0?
Or is it possible to use the LICENSE file of the latest version as the license for ver 0.4.0?
Thanks in advance.

**Comment by ljharb** [comment]
That version is ancient (from August 2013, 11 years ago) and very unsupported; is there a reason you can't upgrade to the latest?

**Comment by itsuki-murata** [comment]
Thank you for your reply.
The reason is that the way is not take time and effort, so I would like to know if it's possible.
I'll consider upgrading to the latest.
Thank you.

**Comment by ljharb** [comment]
Versions are immutable, so it's not possible to add a license file to *any* old version of anything.

I could backport a v0.4.1 with a license file, but that's a lot of effort to spare you from doing what you should have done a decade ago :-)

**Comment by itsuki-murata** [comment]
I understand, thank you for the clarification.
